"""Generate docs/decision-memo.md. Every number is computed here from the committed
historical inputs (the same inputs and rules the dashboard uses), so the memo cannot
drift from the data. `python -m portfolio.pipeline docs` writes it; `verify` checks it."""
from __future__ import annotations

import json
from decimal import ROUND_HALF_UP, Decimal

from . import experiment, leads, paths
from .contract import load_extracts


def _pct(num, den, dp=2) -> str:
    q = Decimal(1).scaleb(-dp)
    return f"{(Decimal(num) * 100 / Decimal(den)).quantize(q, ROUND_HALF_UP)}%"


def _brl(cents: int) -> str:
    return f"BRL {cents // 100:,}.{cents % 100:02d}"


def facts() -> dict:
    x = load_extracts(paths.HISTORICAL_EXTRACTS, "historical")
    m = x.monthly
    S = lambda k: sum(r[k] or 0 for r in m)
    f = {"months": (m[0]["month"], m[-1]["month"]), "orders": S("orders"), "owi": S("orders_with_items"),
         "gmv": S("gmv_c"), "freight": S("freight_c"), "late": S("late"), "delivered": S("delivered"),
         "low": S("low_score"), "reviewed": S("reviewed"), "canceled": S("canceled")}
    f["aov"] = int((Decimal(f["gmv"]) / f["owi"]).quantize(Decimal(1), ROUND_HALF_UP))
    f["naive_late"] = sum(Decimal(r["late"]) * 100 / r["delivered"] for r in m) / len(m)
    f["worst"] = sorted(((Decimal(r["late"]) * 100 / r["delivered"], r["month"], r) for r in m), reverse=True)[:3]
    by = {}
    for r in x.state:
        b = by.setdefault(r["state"], {"orders": 0, "gmv": 0, "freight": 0})
        b["orders"] += r["orders"]
        b["gmv"] += r["gmv_c"] or 0
        b["freight"] += r["freight_c"] or 0
    fs = sorted(((Decimal(v["freight"]) / v["gmv"], k, v) for k, v in by.items()))
    f["freight_lo"], f["freight_hi"] = fs[0], fs[-1]
    doc = json.loads((paths.HISTORICAL_DIR / "criteo_documented_counts.json").read_text())
    c = doc["counts"]
    f["exp"] = experiment.analyse(experiment.ArmCounts(c["n_t"], c["y_t"], c["n_c"], c["y_c"], c["n_exposed"],
                                                       doc["inferred"]["y_exposed"]["value"]))
    f["leads"] = leads.recompute_historical(paths.HISTORICAL_OUTPUTS / "lead_scores_test.csv",
                                            paths.HISTORICAL_OUTPUTS / "lead_scoring_results.csv")
    f["audit"] = leads.audit_historical_split()
    return f


def markdown() -> str:
    f = facts()
    e = f["exp"]
    itt, cace = e["itt"], e["cace"]
    pp = lambda v, dp=4: f"{'+' if v >= 0 else ''}{100 * v:.{dp}f} pp"
    lr, gb = f["leads"]["models"]
    worst = ", ".join(f"{mo} ({_pct(r['late'], r['delivered'])})" for _, mo, r in f["worst"])
    lo_s, hi_s = f["freight_lo"], f["freight_hi"]
    a = f["audit"]
    return f"""# Decision memo

_Generated by `python -m portfolio.pipeline docs` from the committed historical inputs
(prior full-data run, 2026-07-16; recomputed, not re-executed). The dashboard's "Decision memo"
view shows the same figures. The marketplace study and the ad experiment are separate and are never joined._

**Bottom line.** Nothing here proves that any intervention would raise revenue. The data supports
three investigations and one budgeting rule, each written as a test to run rather than a gain
already demonstrated.

## What the data shows

| Finding | Number | Denominator / scope |
|---|---|---|
| Orders, {f['months'][0]} to {f['months'][1]} | {f['orders']:,} | analysis window (the prior run excluded 349 of 99,441 orders outside it) |
| GMV (items + freight) | {_brl(f['gmv'])} | summed in integer cents |
| Average order value | {_brl(f['aov'])} | GMV ÷ {f['owi']:,} orders **with items** |
| Late-delivery rate | {_pct(f['late'], f['delivered'])} | {f['late']:,} late ÷ {f['delivered']:,} **delivered** orders (weighted) |
| Mean of the 20 monthly late rates | {f['naive_late'].quantize(Decimal('0.01'), ROUND_HALF_UP)}% | shown only as a counterexample: it weights every month equally |
| Worst late-delivery months | {worst} | per-month late ÷ delivered |
| Low-review rate (latest score ≤ 2) | {_pct(f['low'], f['reviewed'])} | {f['low']:,} ÷ {f['reviewed']:,} reviewed orders (monthly numerators inferred as unique integers) |
| Freight share of GMV by customer state | {_pct(lo_s[2]['freight'], lo_s[2]['gmv'], 1)} ({lo_s[1]}, {lo_s[2]['orders']:,} orders) to {_pct(hi_s[2]['freight'], hi_s[2]['gmv'], 1)} ({hi_s[1]}, {hi_s[2]['orders']:,} orders) | freight ÷ GMV; a price-mix measure, not margin |
| Ad-experiment ITT (assigned vs control) | {pp(itt['diff'])} (95% CI {pp(itt['ci'][0])} to {pp(itt['ci'][1])}) | {e['counts']['n_t']:,} treated, {e['counts']['n_c']:,} control |
| ≈ incremental conversions | {1000 * itt['diff']:.2f} per 1,000 assigned users | from the ITT only |
| Share of treated users exposed | {100 * cace['compliance']:.2f}% | exposed ÷ treated |
| Lead ranking (logistic regression, retrospective) | AUC {lr['auc']:.3f}; top 265: {lr['top_expected_hits']:.2f} expected hits (any tie-break {lr['top_min_hits']}–{lr['top_max_hits']}) vs {f['leads']['prevalence'] * 265:.1f} at random | Apr–May 2018 held-out cohort, 2,655 leads |

## Recommendations (investigations and experiments, not promised gains)

1. **Diagnose the late-delivery spikes.** Break the worst months down by seller, carrier region and
   category (needs order-level data), then test one operational change (for example a padded
   delivery estimate or a carrier switch on the worst lanes) in a randomised rollout, measuring the
   late rate and review scores. The monthly co-movement of late deliveries and low reviews is a
   hypothesis until then.
2. **Test freight pricing where it bites.** States with the highest freight share are candidates
   for a freight-subsidy or free-shipping-threshold experiment. The data holds no cost or margin, so
   the experiment must record both before anyone can say a subsidy pays. The extreme ({hi_s[1]}) rests
   on {hi_s[2]['orders']:,} orders.
3. **Re-evaluate lead scoring prospectively.** The historical model trained on labels that were not
   complete at its cut (training outcome windows ended {a['outcome_windows_end_between'][0]} to
   {a['outcome_windows_end_between'][1]}; the cut was {a['cut']}) and used a look-ahead page-volume
   feature. Retrain with the as-of design and point-in-time features (implemented; demonstrated on
   synthetic data), then run a randomised prioritisation test (score order vs current order) before
   claiming extra wins.
4. **Budget ads on the ITT, not on exposure.** Use the ITT and its interval with real cost and margin
   (the dashboard's break-even calculator shows the arithmetic: each unit of cost per 1,000 assigned
   users needs about {1 / (1000 * itt['diff']):.3f} units of value per incremental conversion). Do not
   budget on the naive exposed-vs-control lift ({100 * e['naive']['relative']:,.2f}%) or on CACE
   ({pp(cace['cace'], 3)}, compliers only). Most assigned users were never exposed; find out why before
   scaling.

## What we cannot claim

- Any causal effect of delivery speed, freight or payment method on sales or reviews: the marketplace
  data has no randomised treatment.
- Any ROI: neither dataset holds costs or margins.
- That the reconstructed dbt intermediate layer reproduces the historical numbers: it is validated
  on synthetic data only, because the raw files were not available to this build.
- Why no 2017 lead converted within 90 days: the regime break is observed; its cause is unknown.
- That the 90-day labels were completely observed: the outcome-observation cutoff is an assumption.
- Anything about the real marketplace or ad experiment from the synthetic sample.
"""
